backend:
  name: github
  repo: Azouz678/electros-store
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "categories"
    label: "الفئات"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "اسم الفئة", name: "title", widget: "string" }

  - name: "products"
    label: "المنتجات"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "اسم المنتج", name: "title", widget: "string" }
      - { label: "السعر", name: "price", widget: "string" }
      - { label: "الصورة", name: "image", widget: "image" }
      - { label: "الفئة (slug)", name: "category", widget: "string" }
      - { label: "الوصف", name: "body", widget: "markdown" }